name: Deploy MkDocs to GitHub Pages

on:
  # Triggers the workflow on pushes to the main branch
  push:
    branches:
      - main  # Change 'main' to 'master' if your main branch is called 'master'
  
  # Allows you to manually run the workflow from the Actions tab
  workflow_dispatch:

# Sets the permissions required for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material
      
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build site with MkDocs
        run: mkdocs build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # MkDocs builds the static files into the 'site' directory by default
          path: './site'
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4