site_name: Extra Medium
site_url: https://bgarrison2.github.io/extra-medium
site-base-url: /extra-medium/

nav:
  - Home: 
    - Home: index.md
    - About: about.md
   
  - Guides: 
    - Getting started: guides/index.md
    - Ride:
      - Set up tubeless tires: guides/ride/set-up-tubeless-tires.md
    - Extract:
      - Espresso gear: guides/extract/espresso-gear.md
        
  - Recipes:
    - Chicken Satay Chili: recipes/chicken-satay-chili.md
    - Pickled Red Onions: recipes/pickled-onions.md
    
 
theme:
  name: material
  
  logo: assets/logo.png
  
  favicon: assets/logo.png
  
  # Optional: Choose a color scheme (e.g., slate for dark mode)
  palette:
    scheme: default
    primary: white
    accent: blue
    
  # Optional: Show the file's last update date
  features:
    - content.action.edit
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    - navigation.expand
    - navigation.path
    



    
